### ISSUE TITLE
Add more test coverage

### ISSUE THREAD

**Issue by micahu-zz** [micahu/splitter#6]
- test balance change on odd number deposits
- add balance test for carol

**Comment by micahu-zz** [comment]
See comments on lines 66-69 of commit 44ecc35.
Still having trouble verifying that the owner's balance was incremented with the remainder of the split.
I've added a task to add some js scripts to help debugging in geth to test allowances there #7

**Comment by micahu-zz** [comment]
some more context: 
line 67 is using the BigNumber equality check, the equivalent of javascript's '=='
line 69 is using the chai equality check, and is the equivalent of javascript's '==='
```
66    // Unsure why this passes:
67    expect(new BigNumber(ownerBefore.plus(one)).isEqualTo(ownerAfter))
68    // and this fails:
69    expect(new BigNumber(ownerBefore.plus(one))).is.equal(ownerAfter)
```

**Comment by xavierlepretre** [comment]
I typically do `assert.strictEqual(new BigNumber(ownerBefore.plus(one)).toString(10), ownerAfter.toString(10))`

**Comment by xavierlepretre** [comment]
Also try teaching chai to use BigNumber: http://www.chaijs.com/plugins/chai-bignumber/
